# docker-compose 파일의 버전을 정의
version: '3.8'

# 이 파일로 실행할 모든 서비스(컨테이너)들을 정의
services:
  
  # 1. User-Service (PHP/Apache)
  user-service:
    build: .  # 현재 폴더(user)의 Dockerfile을 사용해 이미지를 빌드
    container_name: userapi # 컨테이너 이름
    ports:
      - "8080:80" # Mac의 8080 포트를 컨테이너 80 포트로 연결
    volumes:
      - .:/var/www/html # 현재 폴더(user)를 컨테이너 웹 서버 폴더와 실시간 동기화
    networks:
      - finalexam # finalexam 네트워크에 연결
    depends_on:
      - mysql
      - redis
      
  # 2. MySQL 데이터베이스
  mysql:
    image: mysql:8.2
    container_name: mysql # database.php가 찾는 호스트 이름
    networks:
      - finalexam
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: php-mysql
      MYSQL_USER: php-mysql
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql-data:/var/lib/mysql # DB 데이터를 Mac에 저장 (컨테이너 삭제돼도 보존됨)
      # init 폴더의 .sql 파일을 /docker-entrypoint-initdb.d/ 에 연결
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  # 3. Redis 세션 스토어
  redis:
    image: redis:7-alpine
    container_name: redis # redis_session.php가 찾는 호스트 이름
    networks:
      - finalexam
    volumes:
      - redis-data:/data

# Docker가 사용할 네트워크를 정의
networks:
  finalexam:
    driver: bridge # 기본 네트워크 드라이버

# Docker가 사용할 볼륨(데이터 저장소)을 정의
volumes:
  mysql-data:
  redis-data: